---
- name: Install nginx and do the needed
  hosts: A2
  become: true

  tasks:

    - name: Update packages
      yum:
        name: '*'
        state: latest
      become: true

    - name: Install Nginx
      yum:
        name: nginx
        state: present
      become: true

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Check Nginx status
      service:
        name: nginx
        state: restarted
        enabled: yes
      register: nginx_status

    - name: Set permissions and update index.html
      shell: |
        sudo chmod 007 /usr/share/nginx/html/index.html
        sudo echo "Hello this is task-2 using ansible playbook" >> /usr/share/nginx/html/index.html
      become: true
      when: nginx_status.changed
